//http://stackoverflow.com/questions/31548067/what-does-pragma-keylist-keyword-do
//Note: long - Defines a long integer data type, equivalent to IDL/CDR long. A 32-bit signed long integer value. (RTI)
module messages
{
    struct RobotControl
    {
        long id;
        long x;
        long y;
        long z;
        long key; //@key
    };
#pragma keylist RobotControl key

    struct RobotAlarm
    {
        long id;
        long alarm1;
        long alarm2;
        long key; //@key
    };
#pragma keylist RobotAlarm key

    struct RobotSensor
    {
        long id;
        string data;
        long key; //@key
    };
#pragma keylist RobotSensor key
};
