//http://stackoverflow.com/questions/31548067/what-does-pragma-keylist-keyword-do
//Note: long - Defines a long integer data type, equivalent to IDL/CDR long. A 32-bit signed long integer value. (RTI)
module messages
{
    struct RobotControl
    {
        long id; //@key
        long x;
        long y;
        long z;
    };
#pragma keylist RobotControl id

    struct RobotAlarm
    {
        long id; //@key
        long alarm1;
        long alarm2;
    };
#pragma keylist RobotAlarm id

    struct RobotSensor
    {
        long id; //@key
        string data;
    };
#pragma keylist RobotSensor id
};
